### ISSUE TITLE
或许需要更新 VitePress 版本了

### ISSUE THREAD

**Issue by RealBigBrownBear** [luhaifeng666/obsidian-plugin-docs-zh#203]
这两天使用 VitePress 编译文档的时候，不知道是不是版本比较老，VitePress 官网放出来的一些新特性没有生效，比如：

- [Code Group](https://vitepress.vuejs.org/guide/markdown#code-groups)
- [Line Highlighting in Code Blocks](https://vitepress.vuejs.org/guide/markdown#line-highlighting-in-code-blocks)

**Comment by luhaifeng666** [comment]
是的，我之前锁死版本了，我来升级下，正好先前有些 Code group 可以加上了。感谢提醒~

**Comment by luhaifeng666** [comment]
VitePress 已更新至目前最新版本，并解除版本锁定。

**Comment by RealBigBrownBear** [comment]
> VitePress 已更新至目前最新版本，并解除版本锁定。

哈哈，感觉更新到最新版本用了 Code Block 的新特性后，整个文档都焕然一新了 😁

**Comment by luhaifeng666** [comment]
是的，之前文档用的 VuePress，本来是支持 Code Group 的，后来用 VitePress 重构之后，发现特性不见了，这会儿支持之后版面要清爽不少~
