### ISSUE TITLE
处理器问题

### ISSUE THREAD

**Issue by myliwenbo** [luhaifeng666/obsidian-plugin-docs-zh#72]
registerMarkdownPostProcessor 后处理好像是一个标签一个标签加载的，有加载完之后的处理器嘛

**Comment by luhaifeng666** [comment]
看了下代码定义，好像是没有的：
<img width="823" alt="image" src="https://user-images.githubusercontent.com/9375823/186058079-f30b8e56-43b1-4b44-a7f0-29ccc2b39bd0.png">
<img width="754" alt="image" src="https://user-images.githubusercontent.com/9375823/186058144-57fc9cb8-9843-4401-92cc-a578cd2c3c06.png">

`registerMarkdownPostProcessor` 以及它接受的 `markdownPostProcessor` 都没有。

你可以去 [这里](https://forum-zh.obsidian.md/) 问问有没有其他的解决办法呢~
